### ISSUE TITLE
support Wireless Card Injection?

### ISSUE THREAD

**Issue by lichaomeng** [ChalesYu/rtl8822bs-aml#1]
Dose  rtl8822bs support Wireless Card Injection? thanks

**Comment by ChalesYu** [comment]
Sorry , I don't know. 
but you can contact realtek for support.(to get a new version driver)
you can also waiting for rtw88 driver support it.
I just found this driver on internet. So I can't helps a lot.

**Comment by lichaomeng** [comment]
thanks

**Comment by lichaomeng** [comment]
thanks anyway!
