### ISSUE TITLE
rtl8822bs aml tv box

### ISSUE THREAD

**Issue by flippke** [ChalesYu/rtl8822bs-aml#4]
I tried this solution (embedding the FW in the header file) for my TV box (Tanix T5 Max, AML  s905x2) after seeing it posted in the armbian forum (forum.armbian.com/topic/15759-please-help-with-rtl8822bs/).

I still get the same error.  I tried to look into the code (I am not a C or linux modeles expert) to see if the FW is being accessed, the issue is when loading into memory, it does the dmem load but imem fails.

I also tried different branches just in case.  Any thoughts on what else I can try?

Thanks for your help and work maintaining this repo!!

**Comment by ChalesYu** [comment]
please try branch `test-5.13.1-20-220325` , this fork from [88x2bu-20210702](https://github.com/morrownr/88x2bu-20210702/issues) .
you can also cherry-pick my commits to support that. maybe I will write a document to explain how to do that.

**Comment by QGB** [comment]
```
uname -a
Linux aml 5.0.2-aml-s905 #5.77 SMP PREEMPT Mon Apr 1 17:23:16 MSK 2019 aarch64 aarch64 aarch64 GNU/Linux

```
could not found 5.0.2 linux-header in apt search?
