### ISSUE TITLE
Does this driver support wifi monitor mode?

### ISSUE THREAD

**Issue by QGB** [ChalesYu/rtl8822bs-aml#6]

**Comment by ChalesYu** [comment]
reference here:
https://github.com/ChalesYu/rtl8822bs-aml/tree/test-5.13.1-20-220617
https://github.com/morrownr/88x2bu

**Comment by QGB** [comment]
此驱动程序正在改进监控模式。需要您的成功或失败报告。如果您还没有购买与监控模式一起使用的适配器，那么可以使用已知可以很好地与监控模式配合使用的适配器。对于那些希望购买监视器模式适配器的人，我的建议是购买基于以下芯片组的适配器：mt7612u、mt7610u、rtl8812au 和 rtl8811au。我按优先顺序对适配器的具体建议是：

ALFA AWUS036ACHM - 远程 - 内核驱动程序

ALFA AWUS036ACM - 内核驱动程序

ALFA AWUS036ACH - 长距离 -[驱动器](https://github.com/morrownr/8812au-20210629)

阿尔法 AWUS036ACS -[驱动程序](https://github.com/morrownr/8821au-20210708)

要提问，请前往[USB-WiFi](https://github.com/morrownr/USB-WiFi) 并在Discussions或中发帖Issues。

**Comment by QGB** [comment]
@ChalesYu 

```

root@aml:~/rtl8822bs-aml# uname -a
Linux aml 5.0.2-aml-s905 #5.77 SMP PREEMPT Mon Apr 1 17:23:16 MSK 2019 aarch64 aarch64 aarch64 GNU/Linux



root@aml:~/rtl8822bs-aml# make
make ARCH=arm64 CROSS_COMPILE= -C  M=/root/rtl8822bs-aml  modules
make[1]: *** M=/root/rtl8822bs-aml: No such file or directory.  Stop.
Makefile:2014: recipe for target 'modules' failed
make: *** [modules] Error 2

```

**Comment by ChalesYu** [comment]
try 
`make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-  KSRC=/lib/modules/5.0.2-aml-s905/build  M=~/rtl8822bs-aml  modules`

or see #7 , try compile rtl8822bu drivers

**Comment by QGB** [comment]
@ChalesYu 

```

root@aml:~/rtl8822bs-aml# make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- KSRC=/lib/modules/5.0.2-aml-s905/build M=~/rtl8822bs-aml modules
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -C /lib/modules/5.0.2-aml-s905/build M=/root/rtl8822bs-aml  modules
make[1]: *** /lib/modules/5.0.2-aml-s905/build: No such file or directory.  Stop.
Makefile:2014: recipe for target 'modules' failed
make: *** [modules] Error 2

root@aml:~/rtl8822bs-aml# ls /lib/modules/5.0.2-aml-s905/
kernel         modules.alias.bin  modules.builtin.bin  modules.dep.bin  modules.order    modules.symbols
modules.alias  modules.builtin    modules.dep          modules.devname  modules.softdep  modules.symbols.bin



root@aml:~/rtl8822bs-aml# make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-  M=~/rtl8822bs-aml modules                           make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -C  M=/root/rtl8822bs-aml  modules
make[1]: *** M=/root/rtl8822bs-aml: No such file or directory.  Stop.
Makefile:2014: recipe for target 'modules' failed
make: *** [modules] Error 2

```

**Comment by ChalesYu** [comment]
It seems you have a linux-header issue, you may need to update your kernel version to fix that.

Now, you need to compile rtw88 driver from https://github.com/lwfinger/rtw88 , you can send your issue to https://github.com/lwfinger/rtw88/issues when you have compile error.
Then, you can try `rtw88-sdio-test` branch from my repo.
