### ISSUE TITLE
Script issue

### ISSUE THREAD

**Issue by Kamilus2410** [ChalesYu/rtl8822bs-aml#7]
Hello
I'm trying to install RTL8822BS driver on Z28 pro tv box with RK3328 processor running on Armbian. Are you able to help me with preparing makefile config to work with this system? I'm trying to use CONFIG_PLATFORM_AML_S905_LINUX = y but I'm getting this error:
make -j2
make ARCH= CROSS_COMPILE= -C  M=/root/rtl8822bs-aml  modules
make[1]: *** M=/root/rtl8822bs-aml: No such file or directory.  Stop.
make: *** [Makefile:2019: modules] Error 2

Is there anything we could do? 
cd
root@z28pro:~# ls
rtl8822bs-aml  rtl8822bs-aml-master  rtl88x2bu

The folder from your github seems to be in correct location.

**Comment by ChalesYu** [comment]
Oh, I don't have any board with rockchip platform. But I can give you some hint.

you need try to compile rtl8822bu driver at here - https://github.com/morrownr/88x2bu-20210702
then add some commits to make that driver to support rtl8822bs  - https://github.com/ChalesYu/rtl8822bs-aml/commits/test-5.13.1-20-211113

And, you can also test this rtw88 driver
https://github.com/xdarklight/linux/commits/rtw88-test-20220611
