### ISSUE TITLE
Unable to build on armbian

### ISSUE THREAD

**Issue by n0th1n6** [ChalesYu/rtl8822bs-aml#8]
I am trying to build it on a RK3328 TV Box with armbian installed. Here is what I am getting when I am trying to build

> make ARCH=arm CROSS_COMPILE=aarch64-linux-gnu- -C /lib/modules/6.2.16-media/build M=/root/rtl8822bs-aml  modules
make[1]: Entering directory '/usr/src/linux-headers-6.2.16-media'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
  You are using:           aarch64-linux-gnu-gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
  CC [M]  /root/rtl8822bs-aml/core/rtw_cmd.o
aarch64-linux-gnu-gcc: error: unrecognized argument in option ‘-mabi=apcs-gnu’
aarch64-linux-gnu-gcc: note: valid arguments to ‘-mabi=’ are: ilp32 lp64
  CC [M]  /root/rtl8822bs-aml/core/rtw_security.o
aarch64-linux-gnu-gcc: error: unrecognized command-line option ‘-mapcs’
aarch64-linux-gnu-gcc: error: unrecognized argument in option ‘-mabi=apcs-gnu’
aarch64-linux-gnu-gcc: note: valid arguments to ‘-mabi=’ are: ilp32 lp64
aarch64-linux-gnu-gcc: error: unrecognized command-line option ‘-mapcs’
aarch64-linux-gnu-gcc: error: unrecognized command-line option ‘-mno-sched-prolog’
aarch64-linux-gnu-gcc: error: unrecognized command-line option ‘-mno-sched-prolog’
aarch64-linux-gnu-gcc: error: unrecognized command-line option ‘-msoft-float’
make[2]: *** [scripts/Makefile.build:252: /root/rtl8822bs-aml/core/rtw_cmd.o] Error 1
make[2]: *** Waiting for unfinished jobs....
aarch64-linux-gnu-gcc: error: unrecognized command-line option ‘-msoft-float’
make[2]: *** [scripts/Makefile.build:252: /root/rtl8822bs-aml/core/rtw_security.o] Error 1
make[1]: *** [Makefile:2021: /root/rtl8822bs-aml] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.2.16-media'
make: *** [Makefile:2018: modules] Error 2

**Comment by ChalesYu** [comment]
ARCH should be arm64 but not `ARCH=arm` ,as rk3328 is a arm64 device but not arm32.
So you need use `make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -C /lib/modules/6.2.16-media/build M=/root/rtl8822bs-aml modules`

**Comment by thanhhieuqb** [comment]
you can make guide to build for armbian on tv box?

**Comment by ChalesYu** [comment]
No, The guide is already write by other people, can use the same way in other realtek wifi vendor driver.
https://github.com/morrownr/88x2bu-20210702
